### ISSUE TITLE
Transparent color is not an eraser

### ISSUE THREAD

**Issue by kjensenxz** [adedomin/moose#10]
When drawing with the transparent color, it does not act as an eraser. 
This has some implications for the fill tool; when filling a void region that borders a transparent pixel, the transparent pixel is unchanged.

Steps to duplicate:

- Paint a transparent pixel on the canvas at https://moose.ghetty.space/
- Use the fill tool with a color on another "transparent" (void) pixel

Reported by @inexist3nce; duplicated.

**Comment by inexist3nce** [comment]
ur too vague mate
```
<ine> the eraser is its own color seems like
<ine> erased pixels and not-drawn pixels are two diff things
<ine> so if you use the fill function on one it doesnt go to the other one
```

**Comment by adedomin** [comment]
See Above Link ^. this belongs there. Will fix soon. thanks for the report.

**Comment by adedomin** [comment]
this WAS indeed a moose bug, reoped.
