### ISSUE TITLE
option to exclude dicks

### ISSUE THREAD

**Issue by inexist3nce** [adedomin/moose#8]
there are currently a lot of moose with a low quality dick on them, such as these:

- BLC
- penis!
- penis line!
- penis line
- PENIS PARTY - by vap0r
- ur mom last nite
- penetration
- 37
- blue balls
- chode meets bush
- wewewewew
- monroe watching prussian
- midna swc
- midna eating some bbc
- teaching gnu
- poor gnu
- real quintz tonight
- longdick2
- longdickislong
- fucking
- trouser snake
- bigdick
- cock
- hd bbc
- tos
- ethan gangrene dick2
- Ethan opening wide
- hikilakas father
- underdoge CUM EDITION
- wait2
- 2
- ethan lol
- luis eating
- oh my
- beg
- on your knees
- cookie
- goku lol2
- runescape
- fenex lol
- prussian lol
- charmander lol
- svitkona lol
- ine FAKE
- immature
- Ethan Noodledick
- truly the pinnacle of shitposting methods
- bonner
- Svitkona
- purple cock pissing fire swastika
- CSIS
- CSLS
- CIA
- CIA_
- ochinchin
- goblin_cock
- todd
- benis
- fart
- cum on
- benis :DDDDDD
- erect
- wener
- dick head
- penis
- One-eyed Willy2
- One-eyed Willy
- underdoge
- underdog
- KolonelPanic throb
- noodle
- fuckhat
- luis is really gay
- jeffree
- jeff
- jeffrey
- penis!!
- BLC
- DraconicIce

and others i guess. i suggest adding a ".moose" command that allows excluding low effort dick jokes

edit: added more dicks
edit2: updated dicks

**Comment by inexist3nce** [comment]
this isnt going to happen is it

more dicks:
- ensorcell
- noose

**Comment by adedomin** [comment]
I mean what do you expect it to do? I can add moose tagging and then filter by tags. but that still depends on some manual effort.

if you can devise some kind of filter. I would more than love to implement it.

**Comment by inexist3nce** [comment]
i guess this cant be done without tags and humans moderating them
